baseUrl = "https://hsj1993.cn"
languageCode = "en-us"
title = "Shimmer Blog"

[markup]
    [markup.highlight]
        style = "dracula"
        tabWidth = 2

[taxonomies]
    tag = "tags"
    mood = "moods"
    
[params]
    cdnUrl = "http://images.hsj1993.cn"
    custom_css = ["css/normalize.css", "css/global.css"]
