baseURL = "https://silly-swirles-56d6f6.netlify.app/"
languageCode = "en-us"
title = "My New Hugo Site"

[taxonomies]
    tag = "tags"
    mood = "moods"
[params]
    custom_css = ["css/normalize.css"]
